[auth]
mongodb_uri = "mongodb+srv://ZeekAdmin:Interns2026@cluster0.1puh22d.mongodb.net/?appName=Cluster0"
mongodb_db = "zeek_auth"
bootstrap_admin_username = "admin"
bootstrap_admin_password = "AdminPass123!"
