[auth]
mongodb_uri = "mongodb+srv://ZeekAdmin:Interns2026@cluster0.1puh22d.mongodb.net/?appName=Cluster0"
mongodb_db = "zeek_auth"
bootstrap_admin_username = "joshuasebastian0000@gmail.com"
bootstrap_admin_password = "AdminPass123!"
allowed_google_emails = ["joshuasebastian0000@gmail.com"]
google_oauth_enabled = false
google_client_id = "262013512528-s1lbcqmro9623l0j5akshcoq8o1dso09.apps.googleusercontent.com"
google_client_secret = "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"
google_redirect_uri = "http://localhost:8501"
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_username = "bnszeek@gmail.com"
smtp_password = "kojw mscl jdxj hgpr"
smtp_from_email = "bnszeek@gmail.com"
smtp_from_name = "Zeek Admin"
smtp_use_tls = true
smtp_use_ssl = false



db_backend = "mysql"

mysql_host = "127.0.0.1"
mysql_port = 3307
mysql_user = "upanginterns"
mysql_password = "Upang123!@#"
mysql_database = "upanginterns"
